version: '3.0'
services:
  frontend:
    container_name: gym-app-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/static:/app/frontend/static
      - ./frontend/vite.config.js:/app/frontend/vite.config.js
      - ./frontend/svelte.config.js:/app/frontend/svelte.config.js
  backend:
    container_name: gym-app-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "8080:8080"
    restart: always
    volumes:
      - .:/app
  db:
    image: mysql:latest
    container_name: gym-app-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    
volumes:
  my-db:

